# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_material.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomMaterial(object):
    def setupUi(self, CustomMaterial):
        CustomMaterial.setObjectName("CustomMaterial")
        CustomMaterial.resize(384, 276)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo_fih.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CustomMaterial.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CustomMaterial)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_use_material = QtWidgets.QPushButton(self.centralwidget)
        self.btn_use_material.setGeometry(QtCore.QRect(160, 190, 75, 23))
        self.btn_use_material.setObjectName("btn_use_material")
        self.cp_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cp_box.setGeometry(QtCore.QRect(200, 70, 141, 22))
        self.cp_box.setDecimals(4)
        self.cp_box.setMaximum(100000.0)
        self.cp_box.setObjectName("cp_box")
        self.rho_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rho_box.setGeometry(QtCore.QRect(200, 110, 141, 22))
        self.rho_box.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.rho_box.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.rho_box.setProperty("showGroupSeparator", False)
        self.rho_box.setPrefix("")
        self.rho_box.setSuffix("")
        self.rho_box.setDecimals(4)
        self.rho_box.setMaximum(10000.0)
        self.rho_box.setObjectName("rho_box")
        self.k_box = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.k_box.setGeometry(QtCore.QRect(200, 150, 141, 22))
        self.k_box.setDecimals(4)
        self.k_box.setMaximum(1000000.0)
        self.k_box.setObjectName("k_box")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 50, 181, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 20, 111, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 121, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 151, 20))
        self.label_3.setObjectName("label_3")
        self.material_name = QtWidgets.QLineEdit(self.centralwidget)
        self.material_name.setGeometry(QtCore.QRect(200, 30, 141, 20))
        self.material_name.setObjectName("material_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 30, 31, 20))
        self.label_4.setObjectName("label_4")
        CustomMaterial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CustomMaterial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 384, 21))
        self.menubar.setObjectName("menubar")
        CustomMaterial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CustomMaterial)
        self.statusbar.setObjectName("statusbar")
        CustomMaterial.setStatusBar(self.statusbar)

        self.retranslateUi(CustomMaterial)
        QtCore.QMetaObject.connectSlotsByName(CustomMaterial)

    def retranslateUi(self, CustomMaterial):
        _translate = QtCore.QCoreApplication.translate
        CustomMaterial.setWindowTitle(_translate("CustomMaterial", "Custom Material RTA"))
        self.btn_use_material.setText(_translate("CustomMaterial", "Use Material"))
        self.label.setText(_translate("CustomMaterial", " Specific Heat [J/Kg-K]:"))
        self.label_2.setText(_translate("CustomMaterial", "Material density [Kg/m3]:"))
        self.label_3.setText(_translate("CustomMaterial", " Thermal  conductivity [W/m-K]:"))
        self.label_4.setText(_translate("CustomMaterial", "Name:"))
