# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 567)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 130, 311, 391))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layoutRight_h = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutRight_h.setContentsMargins(3, 2, 3, 0)
        self.layoutRight_h.setObjectName("layoutRight_h")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.menuMaterial = QtWidgets.QFontComboBox(self.groupBox)
        self.menuMaterial.setGeometry(QtCore.QRect(10, 60, 281, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuMaterial.sizePolicy().hasHeightForWidth())
        self.menuMaterial.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.menuMaterial.setFont(font)
        self.menuMaterial.setStyleSheet("")
        self.menuMaterial.setObjectName("menuMaterial")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.insulatior_thk = QtWidgets.QLineEdit(self.groupBox)
        self.insulatior_thk.setGeometry(QtCore.QRect(10, 120, 131, 20))
        self.insulatior_thk.setObjectName("insulatior_thk")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(160, 100, 111, 16))
        self.label_4.setObjectName("label_4")
        self.case_thk = QtWidgets.QLineEdit(self.groupBox)
        self.case_thk.setGeometry(QtCore.QRect(160, 120, 131, 20))
        self.case_thk.setObjectName("case_thk")
        self.case_thk_2 = QtWidgets.QLineEdit(self.groupBox)
        self.case_thk_2.setGeometry(QtCore.QRect(10, 180, 131, 20))
        self.case_thk_2.setObjectName("case_thk_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 111, 16))
        self.label_5.setObjectName("label_5")
        self.case_thk_3 = QtWidgets.QLineEdit(self.groupBox)
        self.case_thk_3.setGeometry(QtCore.QRect(160, 180, 131, 20))
        self.case_thk_3.setText("")
        self.case_thk_3.setObjectName("case_thk_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(160, 160, 111, 16))
        self.label_6.setObjectName("label_6")
        self.layoutRight_h.addWidget(self.groupBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(370, 30, 351, 491))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.layoutLeft_h = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutLeft_h.setContentsMargins(0, 0, 0, 0)
        self.layoutLeft_h.setObjectName("layoutLeft_h")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Inputs"))
        self.menuMaterial.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Form", "Material:"))
        self.label_3.setText(_translate("Form", "Insulation tichkness:"))
        self.label_4.setText(_translate("Form", "Case thickness:"))
        self.label_5.setText(_translate("Form", "Radial Steps:"))
        self.label_6.setText(_translate("Form", "Time steps:"))
        self.label.setText(_translate("Form", "Lasc LOGO"))
